footprint: [[-0.4, -0.3], [-0.4, 0.3], [0.4, 0.3], [0.4, -0.3]]
footprint_padding: 0.05

update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5
track_unknown_space: true

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions

static_layer:
   map_topic: /map

obstacle_layer:
   observation_sources: laser
   laser: {sensor_frame: base_laser, data_type: LaserScan, topic: scan, clearing: true, marking: true}

inflation_layer:
    inflation_radius: 1.0
